### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by Scoi4101** [IBM-Security/isam-ansible-playbook-sample#1]
Hello,
This stack is awesome!
But I am struggling with the amount of logging. During development did any formatting or tool help you in formatting the log output to make it more readable?

Thanks

**Comment by ram-ibm** [comment]
group_vars/all/vars.yml has the following setting that allows you to control the level of logs created:
```
# Logging set to maximum, output will not show until -vvv flag is used
log_level: DEBUG
```
Typically the need to run playbooks with the -v (or -vvv) option is needed only during troubleshooting. So I have to ask what are you trying to do that is generating large amounts of logging?

Ansible allows you to log output - that will allow you to capture the logs for analysis using an editor that formats it better.

**Comment by mlu-ibm** [comment]
I think the original question is about how to format the logs. There are some callback plug-ins you may want to check out, for example http://blog.cliffano.com/2014/04/06/human-readable-ansible-playbook-log-output-using-callback-plugin/

**Comment by Scoi4101** [comment]
Yes that was my question thanks.
I will look into it
